export enum Categories {
	TOP = 'TOP',
	WEDDING = 'WEDDING',
	QUINCE = 'QUINCE',
	BABY = 'BABY',
	BOUDOIR = 'BOUDOIR',
	CHILDREN = 'CHILDREN',
	EVENTS = 'EVENTS',
	PRODUCTS = 'PRODUCTS',
	FASHION = 'FASHION',
}
